tob:
  press_space_before_and_after_bot: False


spacecrypto:
  window_name: tob_spacecrypto
  parameters:
    extra_random_wait_time_min_sec: 0
    extra_random_wait_time_max_sec: 30
    spaceship_scroll_limit: 3
  intervals:
    wait_for_spaceship_replacement_sec: 520

lunarush:
  window_name: tob_lunarush
  parameters:
    extra_wait_time_during_dawn_sec: 3600
    battle_not_ended_max_retries: 5
  intervals: 
    wait_for_battle_sec: 45
    wait_for_energy_sec: 7200
    battle_not_ended_yet_sec: 10

bombcrypto:
  window_name: tob_bombcrypto
  intervals: 
    send_heroes_to_work_sec: 1800
    refresh_heroes_positions_sec: 600

# cryptopiece:
#   window_name: tob_cryptopiece
#   intervals:
#     wait_for_stamina_sec: 1800

# agrofarm:  
#   window_name: tob_agrofarm
#   intervals:
#     wait_time_when_no_crop_left_sec: 14400